keys:
  - &admin age1k5swr44adfm6j4xuukqfnfaxf6rhqamk4uhnkmzpxlz93txr3p4syke5c3

creation_rules:
  - path_regex: secrets/ssh-key\.yaml$
    key_groups:
      - age:
          - *master

  - path_regex: secrets/vpn/.\.yaml$
    key_groups:
      - age:
        - *master
