keys:
  - &main age1k5swr44adfm6j4xuukqfnfaxf6rhqamk4uhnkmzpxlz93txr3p4syke5c3

creation_rules:
  - path_regex: .*\.yaml$
    key_groups:
      - age:
          - *main

  - path_regex: vpn/.*\.yaml$
    key_groups:
      - age:
          - *main
